[package]
name = "rust_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datetime = "0.5.2"
chrono = "0.4"
rand = "0.8.5"
itertools = "0.10.5"
shuffle = "0.1.7"